// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUYL_OlCg8E2B9T_naBH5F1IbkqKk20Q',
    appId: '1:1074273212598:web:fab0dd5517181676976e17',
    messagingSenderId: '1074273212598',
    projectId: 'ebed-cb211',
    authDomain: 'ebed-cb211.firebaseapp.com',
    storageBucket: 'ebed-cb211.firebasestorage.app',
    measurementId: 'G-Z1ETDSW1FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-4qU9f8i3lzvWKZ6CR-gGJFh4G-qz8sg',
    appId: '1:1074273212598:android:0ed56e3a7b19cfb0976e17',
    messagingSenderId: '1074273212598',
    projectId: 'ebed-cb211',
    storageBucket: 'ebed-cb211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGf09x3dJBNJyMuIxjYnj_pulZrVJZPro',
    appId: '1:1074273212598:ios:af346181ddd3bb3f976e17',
    messagingSenderId: '1074273212598',
    projectId: 'ebed-cb211',
    storageBucket: 'ebed-cb211.firebasestorage.app',
    iosBundleId: 'com.example.ebed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGf09x3dJBNJyMuIxjYnj_pulZrVJZPro',
    appId: '1:1074273212598:ios:af346181ddd3bb3f976e17',
    messagingSenderId: '1074273212598',
    projectId: 'ebed-cb211',
    storageBucket: 'ebed-cb211.firebasestorage.app',
    iosBundleId: 'com.example.ebed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdUYL_OlCg8E2B9T_naBH5F1IbkqKk20Q',
    appId: '1:1074273212598:web:e8ab0ccc05fcab84976e17',
    messagingSenderId: '1074273212598',
    projectId: 'ebed-cb211',
    authDomain: 'ebed-cb211.firebaseapp.com',
    storageBucket: 'ebed-cb211.firebasestorage.app',
    measurementId: 'G-8MVMQL6KVR',
  );
}
